### ISSUE TITLE
Join the rubyref org?

### ISSUE THREAD

**Issue by geraldb** [rubyreferences/rubyref#10]
Hello,
   This ruby reference is fantastic. Please keep it up. 

  If you're interested you're more than welcome to join the [/rubyref org](https://github.com/rubyref) and move this repo to rubyref/rubyref, for example. 

Cheers. Prost.

**Comment by zverok** [comment]
> This ruby reference is fantastic. Please keep it up.

Thanks.

> If you're interested you're more than welcome to join the /rubyref org and move this repo to rubyref/rubyref, for example.

What would be the point of the join?

**Comment by geraldb** [comment]
> What would be the point of the join?

Good question. In the beginning as written above you get a nicer (shorter) web address - rubyref/rubyref.

Otherwise - not a big difference - the org would now have two owners / people instead of two separate lonley ones. Not trying to be dramatic :-). 

As an alternative I can offer that I rename the "old" rubyref org and than you can rename yours to rubyref. Than you get the nicer (shorter) web address and nothing else changes.

Cheers. Prost.

**Comment by zverok** [comment]
I appreciate your kind proposal, but I am good as is :)
