### ISSUE TITLE
Suggestion: create a `rubyreferences.github.io` repository

### ISSUE THREAD

**Issue by JamesChevalier** [rubyreferences/rubyref#15]
I think you should create a `rubyreferences.github.io` repository so that the main https://rubyreferences.github.io link will work (not be a 404, as it is now).

It would be helpful to have a simple `index.html` file in that repository that links out to https://rubyreferences.github.io/rubyref/ and https://rubyreferences.github.io/rubychanges/.

**Comment by zverok** [comment]
Thanks! Done :) https://github.com/rubyreferences/rubyreferences.github.io
