### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by arbox** [rubyreferences/rubyref#5]
Hello @zverok ,
thank you for this initiative!
Two questions:
- how can we handle Ruby versions in this reference and
- where to put the Changelog between versions?

**Comment by zverok** [comment]
@arbox Thanks!

About Ruby versions, I've considered several approaches, and _for now_ just decided just go with the latest always. E.g. rubyreferences.github.io/rubyref will ALWAYS dedicated to the current version (clearly stated in the page header of each page), and updated as soon as the new version is released. On a scale the reference works (no lists of particular methods and classes and parameters), there probably would be not a lot of changes from version to version. 

In fact, I am planning to see how it will work on the next version (the versions aren't updating THAT fast to make following them manually impossible :)). Maybe I'll insert custom content notices (unless Ruby docs will include them) like "Infinite ranges are introduced in 2.6".

As about changelog, I am not sure. Do you think it should be a part of the reference? Something probably could be invented to implement this... :philosoraptor:

**Comment by zverok** [comment]
Well, I believe this should be marked as resolved:
* I've added "Since Ruby (version)" badges to reference (so it could be read in an informative manner for "current", but also for previous ones);
* I've created separate https://rubyreferences.github.io/rubychanges/ site to explain changes in Ruby.

**Comment by arbox** [comment]
Good news! Thank you for your work again! It's valuable.
