### ISSUE TITLE
"Net::HTTP reference" link is 404

### ISSUE THREAD

**Issue by gimite** [rubyreferences/rubyref#7]
Thanks for creating a nice doc!

I found that "Net::HTTP reference" link here is 404:
https://rubyreferences.github.io/rubyref/stdlib/networking-web/net/http.html

It links to this URL:
https://ruby-doc.org/stdlib-2.5.0/libdoc/net/http/rdoc/Net::HTTP.html
But looks it should be:
https://ruby-doc.org/stdlib-2.5.0/libdoc/net/http/rdoc/Net/HTTP.html

**Comment by zverok** [comment]
Thanks! Fixed and published :)
