### ISSUE TITLE
IRB `__` is undefined

### ISSUE THREAD

**Issue by roman-yarovoy** [rubyreferences/rubyref#9]
https://rubyreferences.github.io/rubyref/intro/irb.html

How to make `__` work in IRB?

```ruby
irb(main):002:0> __
Traceback (most recent call last):
        2: from /Users/yar/.asdf/installs/ruby/2.5.1/bin/irb:11:in `<main>'
        1: from (irb):2
NameError (undefined local variable or method `__' for main:Object)
Did you mean?  _
```
on ruby 2.5.1p57

Or if that page was taken automatically from some source, then would be cool to have a link to that source on every such page, maybe there would be the answer.

**Comment by zverok** [comment]
@roman-yarovoy It is a funny question. Digging deeep in IRB code have provided me with an answer: 
```ruby
IRB.conf[:EVAL_HISTORY] = 100
```
in your `.irbrc` will enable the feature and make `__` variable available. 
You can check that [full IRB docs](http://ruby-doc.org/stdlib-2.5.1/libdoc/irb/rdoc/IRB.html) are completely silent on this little detail (which probably suggests we can do a PR to Ruby ;)), but has some other interesting things. Those things are put in Reference's [Mastering IRB](https://rubyreferences.github.io/rubyref/developing/irb.html) section, which also has the link to [tranditional IRB docs](http://ruby-doc.org/stdlib-2.5.1/libdoc/irb/rdoc/IRB.html).

So... Except for "let's fix IRB docs in Ruby repo", I dunno what to say :)

**Comment by zverok** [comment]
> Except for "let's fix IRB docs in Ruby repo", I dunno what to say :)

Well, so I did it for 2.7: https://ruby-doc.org/stdlib-2.7.0/libdoc/irb/rdoc/IRB.html#module-IRB-label-Session+variables
And now the book also contains an explanation: https://rubyreferences.github.io/rubyref/intro/irb.html#session-variables
